<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model" nsURI="http:///model.ecore" nsPrefix="model">
  <eClassifiers xsi:type="ecore:EClass" name="Terminal">
    <eOperations name="MostraInfo" ordered="false" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="biblioteca" ordered="false"
        lowerBound="1" eType="#//Biblioteca"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Biblioteca">
    <eOperations name="VerificaAtraso" ordered="false" lowerBound="1"/>
    <eOperations name="FazEmprestimo" ordered="false" lowerBound="1"/>
    <eOperations name="CalculaMulta" ordered="false" lowerBound="1"/>
    <eOperations name="CadastraUsuario" ordered="false" lowerBound="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Livro" eSuperTypes="#//Publicacao">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ISBN" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Edicao" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Publicacao">
    <eStructuralFeatures xsi:type="ecore:EReference" name="biblioteca" ordered="false"
        lowerBound="1" eType="#//Biblioteca"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Nome" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Autor" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Area" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Exemplar">
    <eStructuralFeatures xsi:type="ecore:EReference" name="biblioteca" ordered="false"
        lowerBound="1" eType="#//Biblioteca"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Status" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="PeriodoEmprestimo" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Periodico" eSuperTypes="#//Publicacao">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Data" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tese" eSuperTypes="#//Publicacao">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Orientador" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Manual" eSuperTypes="#//Publicacao"/>
  <eClassifiers xsi:type="ecore:EClass" name="Usuario">
    <eOperations name="FazReserva" ordered="false" lowerBound="1"/>
    <eOperations name="CancelaReserva" ordered="false" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="emprestimo" ordered="false"
        lowerBound="1" eType="#//Emprestimo"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Nome" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="NumeroCadastro" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Emprestimo">
    <eOperations name="SolicitaEmprestimo" ordered="false" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="biblioteca" ordered="false"
        lowerBound="1" eType="#//Biblioteca"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Aluno" eSuperTypes="#//Usuario">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="RA" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Curso" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Professor" eSuperTypes="#//Usuario">
    <eOperations name="BloquearExemplar" ordered="false" lowerBound="1"/>
    <eOperations name="DesbloquearExemplar" ordered="false" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Departamento" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Atendente" eSuperTypes="#//Usuario">
    <eOperations name="IncluirExemplares" ordered="false" lowerBound="1"/>
    <eOperations name="ExcluirExemplares" ordered="false" lowerBound="1"/>
    <eOperations name="AtualizarDados" ordered="false" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Cadastro" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Setor" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Funcionario" eSuperTypes="#//Usuario">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Funcao" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TCC" eSuperTypes="#//Publicacao"/>
</ecore:EPackage>
